set(_CATKIN_CURRENT_PACKAGE "rosaria_teleop")
set(rosaria_teleop_MAINTAINER "au <au@todo.todo>")
set(rosaria_teleop_DEPRECATED "")
set(rosaria_teleop_VERSION "0.0.0")
set(rosaria_teleop_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(rosaria_teleop_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(rosaria_teleop_BUILDTOOL_DEPENDS "catkin")